#!/bin/sh
#
# SPDX-License-Identifier: LGPL-2.1-only
#

case $(uname -s) in
Linux)	echo "linux";;
Darwin)	echo "darwin";;
*)	echo >&2 "Unknown result from uname -s: %(uname -s). Aborting."
	exit 1
	;;
esac
